### ISSUE TITLE
Installation failure due to React Native MRZ dependency

### ISSUE THREAD

**Issue by karimStekelenburg** [thecardeaproject/cardea-mobile-holder#4]
I've tried to run the project, however it doesn't install due to the following dependency in `package.json`: `"react-native-mrz": "Indicio-tech/react-native-mrz#1.0.1" `.

Guessing this one isn't public yet 🙃

**Comment by JamesKEbert** [comment]
Ahh my apologies I thought we had made that public already, let me work on getting that available for use. 👍

**Comment by JamesKEbert** [comment]
This should now be public and resolve this issue. Thanks for reporting this, and please reopen if there's additional issues here!
